# Generated by Django 2.2.6 on 2019-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordersId', models.CharField(max_length=100)),
                ('ordersStatus', models.CharField(max_length=10)),
                ('orderCustomerID', models.CharField(default='', max_length=10)),
                ('ordersSellerID', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='statuschangetemptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderIdchange', models.CharField(max_length=100)),
                ('ordersstatuschange', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('password1', models.CharField(default='', max_length=150)),
                ('password2', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(default='customer', max_length=30)),
            ],
        ),
    ]
