# Generated by Django 2.2.6 on 2019-10-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password2',
        ),
    ]
